angular.module("myApp")
    .controller("itemsController",["$scope","itemsService",function($scope,itemsService){
        //itemsService(function(res){
        //    console.log(res);
        //})
        $scope.type="";
        $scope.searchKey="";
        $scope.add=function(item){
            item.count=item.count?(item.count+1):1;
        }
        $scope.sub=function(item){
            item.count=item.count&&item.count>0&&item.count-1;
        }
        $scope.addToCar=function(item){
            //console.log(item);
            itemsService.addCarItem(item);
            //console.log(itemsService.getCarItem())
        }
        $scope.changeType=function(t){
            $scope.type=t;
        }
        itemsService.getAllItems(function(res){
            console.log(res);
            $scope.items=res;
        })
    }])