angular.module("axfApp",["ngRoute"])
    .config(["$routeProvider",function($routeProvider){
        $routeProvider
            .when("/items",{
                templateUrl:"views/items.html"
            })
            .when("/market",{
                templateUrl:"views/market.html"
            })
            .when("/mine",{
                templateUrl:"views/mine.html"
            })
            .otherwise({
                redirectTo:"/items"
            })
    }])
